Fix Docker build (#2)
* Add dist/ to .gitignore

* Use build-base instead of make

So that we have gcc

* Remove -race from tests

-race doesn't support Alpine std lib:

 ---> Running in eee94742d09b
go get -u github.com/kardianos/govendor
govendor sync
govendor test -race -cover -v +local
race_linux_amd64.syso: In function `__sanitizer::InternalAlloc(unsigned long, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<0ul, 140737488355328ull, 0ul, __sanitizer::SizeClassMap<3ul, 4ul, 8ul, 17ul, 64ul, 14ul>, 20ul, __sanitizer::TwoLevelByteMap<32768ull, 4096ull, __sanitizer::NoOpMapUnmapCallback>, __sanitizer::NoOpMapUnmapCallback> >*, unsigned long)':
gotsan.cc:(.text+0x16e1): undefined reference to `__libc_malloc'
race_linux_amd64.syso: In function `__sanitizer::GetArgv()':
gotsan.cc:(.text+0x4543): undefined reference to `__libc_stack_end'
race_linux_amd64.syso: In function `__sanitizer::InternalRealloc(void*, unsigned long, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<0ul, 140737488355328ull, 0ul, __sanitizer::SizeClassMap<3ul, 4ul, 8ul, 17ul, 64ul, 14ul>, 20ul, __sanitizer::TwoLevelByteMap<32768ull, 4096ull, __sanitizer::NoOpMapUnmapCallback>, __sanitizer::NoOpMapUnmapCallback> >*)':
gotsan.cc:(.text+0x7dd0): undefined reference to `__libc_realloc'
race_linux_amd64.syso: In function `__sanitizer::ReExec()':
gotsan.cc:(.text+0xed47): undefined reference to `__libc_stack_end'
race_linux_amd64.syso: In function `__sanitizer::InternalFree(void*, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<0ul, 140737488355328ull, 0ul, __sanitizer::SizeClassMap<3ul, 4ul, 8ul, 17ul, 64ul, 14ul>, 20ul, __sanitizer::TwoLevelByteMap<32768ull, 4096ull, __sanitizer::NoOpMapUnmapCallback>, __sanitizer::NoOpMapUnmapCallback> >*)':
gotsan.cc:(.text+0x7438): undefined reference to `__libc_free'
collect2: error: ld returned 1 exit status
FAIL	github.com/segmentio/tracking-api-chaos/chaos [build failed]
FAIL	github.com/segmentio/tracking-api-chaos/message [build failed]
FAIL	github.com/segmentio/tracking-api-chaos/test [build failed]
Error: exit status 2
make: *** [Makefile:13: test] Error 2
The command '/bin/sh -c make' returned a non-zero code: 2
make: *** [docker] Error 2

* Make the "all" Makefile step the default

* Fix executable copy